### ISSUE TITLE
Add support for 'Header' authentication

### ISSUE THREAD

**Issue by evert** [badgateway/ketting#107]
Some sloppy API's use a header such as `X-API-KEY` to authenticate. It's poor design, but it might be nice to add support for it nonetheless.

**Comment by joshco** [comment]
@evert I am examining ketting for use in this case.  It's only a minor inconvenience, since I can just pass it in via fetchInit.. It took me a while to track it down in the docs, so it might be a good readme note
````
let sloppyOptions = {
  fetchInit: {
    headers: {
      "SLOPPY-API-Token": MY_SLOPPY_TOKEN
     }
   },
   contentType: 'application/json'
}

const ketting = new Ketting(sloppyURL, sloppyOptions)
````

**Comment by evert** [comment]
Hey @joshco , that's a nice workaround. Didn't think about this, and it would have solved a problem for me in the past :P

**Comment by evert** [comment]
I'm going to close this on the basis that it *is* currently possible to do this with fetchInit

**Comment by joshco** [comment]
OK, Here's text for the wiki to document this;

# Header Based Authentication
````
const ketting = new Ketting(url, {
    fetchInit: {
      headers: {
        "FOOI-API-Token": "FOO-SECRET-TOKEN"
      }
    }
  }
)

````

**Comment by evert** [comment]
Ty. Repoening this as a task for updating docs.

**Comment by evert** [comment]
In Ketting 6 (unreleased) this is achievable by writing a simple, custom middleware.
