### ISSUE TITLE
HEAD-hopping for Link header navigation

### ISSUE THREAD

**Issue by mattbishop** [badgateway/ketting#141]
For APIs that use Link headers, it would be nice to specify a `.hop("link-rel")` that uses `HEAD` instead of `GET` to navigate. This is more efficient than GET, not to mention clearer. Imagine:

```js
const shipAddressHops = kettingRoot
  .hop('addresses')
  .hop('shipping');

const homeAddress = await shipAddressHops.follow('home-address');
```

The `hop()` calls would set up a set of steps, but not execute until `follow()` is called. Thus it's a single Promise instead of a bunch of them. Also, the hops are reusable so you don't have to rebuild them every time.

**Comment by evert** [comment]
The idea of resolving a graph only until it's fully needed is very interesting to me, and might also solve something related to Prefer-Push down the line. I also like the use of HEAD and the name `hop`.

So, I'm very on-board with this idea. If you're willing to contribute it, I would definitely accept it. If not, this is something I will probably want to work on at some point.
