### ISSUE TITLE
Passing a relative uri to bookmark fails

### ISSUE THREAD

**Issue by reda-alaoui** [badgateway/ketting#179]
Hi,

Code:
```javascript
new Ketting('api/').go().get();
```
Fails at https://github.com/badgateway/ketting/blob/770ffa9eebc0fbf984dec86182b9fc25255be37e/src/utils/url.web.ts#L14 with:
```
core.js:1 ERROR TypeError: Failed to construct 'URL': Invalid base URL
    at Object.t.resolve (url.web.ts:14)
    at Ketting.go (ketting.ts:84)
```

**Comment by reda-alaoui** [comment]
Note that skipping https://github.com/badgateway/ketting/blob/770ffa9eebc0fbf984dec86182b9fc25255be37e/src/utils/url.web.ts#L13 fixes the issue.

**Comment by evert** [comment]
Duplicates #130
