### ISSUE TITLE
Allow import/export

### ISSUE THREAD

**Issue by benkuly** [badgateway/ketting#183]
I`m searching for a way to use ketting with a state management like mobx or redux without saving a complete ketting class in state?

To realize it, I need to get the response body oder something similar out of ketting and later import it to ketting, when I want to follow a link of a resource.

Example:
* get resource from server with ketting and export it
* save it in mobx or redux store and use it in the view
* a user trigges an action
* action handler uses ketting to import an object from the store (which contains links) to follow and open a link

**Comment by evert** [comment]
It sounds like you just want to store a reference to a `Resource`. This will contain a cached response body, and links to follow.

**Comment by benkuly** [comment]
Not really a reference. I would like to export the complete answer of the server from ketting and import it back into ketting, when I need to. So that ketting can be used stateless.

**Comment by evert** [comment]
The representation() function returns an object that behaves mostly immutable and contains the response body, links, etc.

However, I would not recommend you attempt this. You're actively fighting the design of the library. It's better to store resources. It's unclear what your issue with this is.

On February 26, 2020 7:05:44 AM EST, benkuly <notifications@github.com> wrote:
>Not really a reference. I would like to export the complete answer of
>the server from ketting and import it back into ketting, when I need
>to. So that ketting can be used stateless.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/badgateway/ketting/issues/183#issuecomment-591392748

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by benkuly** [comment]
If we save the resource in the application store, then every view (e. g. react-component) and store-action has access to it and can do server-request. But we want to encapsulate ketting in our Api-class, so we have no dependecy to ketting all over in our code.

**Comment by evert** [comment]
I think you'll just kind of end up fighting the library too much to achieve this, but the best I can tell you is to pass the 'representation' object around, not the resource.

For what it's worth, we do pass resources around to our React component. Our API layer is mostly just responsible for finding the ketting resources and returning them, and it's a very thin layer.

**Comment by evert** [comment]
Take a look at #190
