### ISSUE TITLE
Considering a rewrite: Ketting 6

### ISSUE THREAD

**Issue by evert** [badgateway/ketting#190]
We've been using Ketting for 3 years. There are features I wish to add to Ketting, and it's increasingly painful to make them work into the current design. A lot of these have to do with running it in a browser. I feel it might be time to make some larger changes.

I would like to know, what are you missing? What does/doesn't work well? Any feedback is appreciated. If I'm doing a big BC-breaking rewrite, this is the time to get your pet feature in!

High-level goals:

### Stable state

The underlying motivation is to make it easier to work with React. React really wants a stable 'state', and passing a Resource around as a "prop" makes this painful. The full state of a response from a server includes the body, metadata and links and we don't have one reasonable way to get access to this.

A future version of Ketting might have a `get()` function that no longer returns a response body, but an object representing response body, links, headers and other meta-data.

Then this object might be mutated and as a whole used in the `put()` function. This solves a few underlying issues as well, such as making it easier to a GET request (for example receiving HAL), manipulating links and sending the entire object back again, with the new links

If you call `get()` twice, you get 2 unique objects. Each can be manipulated independently, but each may come from a cache.

```typescript
// basic idea

const resource = await otherResource.follow('author');
const state = await resource.get();

// state has body, links, response headers, etc.
state.body.author = 'Evert';
state.links.add('homepage', 'https://evertpot.com/');

await resource.put(state); // send new state to server
await representation.put(); // alternative? not sure if this is a good idea
```

### Better cache management

We need a central cache for HTTP responses, and not just a cache for responses post-parsing.

We need to be able to support different cache strategies for different situations:

1. The 'forever' cache. This is the current behavior. Very useful for read-only APIs and short-lived processes.
2. The super-short-lived-cache. Maybe 10 seconds. This is better for browsers, as they likely will need very up-to-data data. Furthermore, this is better for folks wanting to completely manage caching on the server-side. It's important that a short-lived cache exists for embedded responses. Those will get parsed out and need to live somewhere until the user needs them. This is very similar to the special cache browsers have for resources pushed via HTTP/2.
3. The true HTTP cache, following all HTTP caching rules. You'll only want this in environments where there is no standard HTTP cache, so .. node.js.
4. The 'never' cache, because why not.

### Other features / goals

1. Subscriptions to changes. If a user does a `PUT` request and send an entire state object, it means we can assume that this is now the the current server-state. This means we can also notify frontends of this new state.
2. Support for discovering links via HEAD requests. Needs to be opt-in, but handy for folks embedding links in headers.
3. Better extension points for things like Siren actions. We basically need people to define their own classes for content-types.

cc @mihok @simistern @aradsziw @matchilling @merrickread @juhangsin @mattbishop @gabesullice @philsturgeon (hope i didn't miss anyone)

**Comment by evert** [comment]
First draft of the API:

```typescript
interface Resource {

  uri: string;

  follow(rel: string): FollowPromise<Resource>
  followAll(rel: string): FollowPromise<Resource[]>
  go(relativeUri: string): Resource;

  get(): Promise<State<any>>;
  head(): Promise<HeadState>;
  put(state: State<any>): Promise<void>;
  delete(): Promise<void>
  post(request: PostRequest): Promise<null|Resource>;
  patch(request: PatchRequest): Promise<void>;

  // When we have a new state, due to a PUT request, or a new
  // GET request.
  on(event: 'state', handler: (res: Resource, state: State<any>) => void): void;

  // When the cache times out, or when a non-safe method is executed.
  on(event: 'expire', handler: (res: Resource) => void): void;

  // Basically the full fetch feature but the url is optional
  fetch(): any;

}

interface State<T> {

  body: T;
  links: Links;

  // Open question. Which headers are important?
  // Many aren't. Think: Connection
  // Some are critical, such as Content-Type.
  // Which get sent back, which don't? Manybe just the `Content-*` headers?
  headers: Headers;
  timeStamp: number;

}

// Example of an extended State
interface SirenState<T> extends State<T> {

  // example of an extended state object.
  action(name: string): SirenAction;
  actions(): SirenAction[];

}

// Example of an action
interface SirenAction {
  name: string;
  href: string;
  method: string;
  fields: any[]; // too lazy to write out
  submit(params: any[]): Promise<Resource>;
}

interface HeadState {

  links: Links;
  headers: Headers;
  timeStamp: number;

}

interface Client {
  // This is the old 'main' object. I think this should become a
  // global/singleton. This has tradeoffs but also causes a LOT less objects
  // to be passed around everywhere.
  
  // All the auth config
  auth: any;

  // Baseurl can be inferred from document.location in browsers, but this is
  // the old 'bookmark'
  baseUrl: string;
  
  follow(rel: string): FollowPromise<Resource>
  followAll(rel: string): FollowPromise<Resource[]>
  go(relativeUri: string): Resource;

  // Having a global resource cache is still good
  resourceCache: Map<string, Resource>;

  // HTTP cache. Too big to write out now
  httpCache: any;

}


// This will be a 'PromiseLike'
interface FollowPromise<T> {

  follow(rel: string): FollowPromise<Resource>;
  followAll(rel: string): FollowPromise<Resource>;

  prefetch(): this;
  preferTransclude(): this;
  preferPush(): this;

  // Trigger HEAD request
  useHead(): this;

  // These signatures are not complete:
  then(): Promise<T>;
  catch(): Promise<T>;
  finally(): Promise<T>;
}

interface Links {

  get(rel: string): Link | null;
  getMany(rel: string): Link[];
  has(rel: string): boolean;
  set(link: Link): void;

}

interface Headers {

  get(name: string): string|null;
  getMany(rel: string): string[];
  has(name: string): boolean;
  set(name: string, value: string): void;

}

interface Link {
  rel: string;
  href: string;
  'type'?: string;
  title?: string;
  anchor?: string;
  hreflang?: string;
  [attr: string]: string|undefined;
}

interface PostRequest {
  body: any;
  headers: Headers;
}

type PatchRequest = PostRequest;
```

**Comment by awwright** [comment]
We might have different motivations, but I want to share one of the concepts I’ve been thinking of, I think I would best describe it as an API driven generic hypermedia client. Think similar in function to a Web browser, but headless, and driven by an API and hypermedia features.

In short, imagine you navigate to an entry point:

const endpoint = Browser.Enter(‘http://www.youtypeitwepostit.com/‘);

And once you have that, you can do the variety of things supported by hypermedia, like following links, submitting forms, editing resources, and of course downloading stuff.

The following features would be included:

* Navigating link relationships
* Aggregating collections across paged resources
* Identifying and filling out URI templates (e.g. <form method=“get”>)
* Identifying and filling out forms (e.g. <form method=“post”>)
* Extensible mechanisms for parsing documents (each would define how to identify a form, template, paged collection, …)
* Extensible mechanisms for extracting links (HTTP, HTML, RDFa, JSON Hyper-schema, …)
* Extensible cache mechanism, so multiple instances can share a shared and/or private cache
* Automatic handling of HTTP redirects
* Accept a callback to correct URLs that returned Moved Permanently and Permanent Redirect; which would provide the old and new URI, and the response body which may contain additional information on the redirect, and the user would update their database accordingly.
* Automatic handling of throttling and Retry-After headers
* Automatic retry of PATCH requests as a PUT request, if the server does not have support
* Automatic retry of aborted downloads with a Range + If-Range request
* Monitoring of resource changes with If-Match, If-Modified-Since, and push events (maybe support CoAP's SUBSCRIBE method)
* Support for Code-on-Demand; the ability to apply stylesheets and scripts to downloaded resources

**Comment by evert** [comment]
@awwright , that's great feedback! Some of those things we got, some of them are planned and others I've never really given thought. I wanna go over each point:

> const endpoint = Browser.Enter('http://www.youtypeitwepostit.com/');

This broadly exists, but you do `const resource = client.go('http://www.youtypeitwepostit.com/');`

> Navigating link relationships

Got this

> Aggregating collections across paged resources

We do and we don't. You can basically follow `next` links. I would like add something that makes this a bit nicer to work with, but my first thought was doing this via a react component. We've needed it here first, and the main use-case was infinite scroll.

> Identifying and filling out URI templates (e.g. <form method=“get”>)
> Identifying and filling out forms (e.g. <form method=“post”>)

I want this. We parse HTML links but not yet forms. This is definitely planned (along with Siren actions and other formats that support this).

> Extensible mechanisms for parsing documents (each would define how to identify a form, template, paged collection, …)

This exists, but will be better in the new version.

> Extensible mechanisms for extracting links (HTTP, HTML, RDFa, JSON Hyper-schema, …)

Got this, but not for all these formats.

> Extensible cache mechanism, so multiple instances can share a shared and/or private cache

This will be better in the next version, but will mainly operate as a private cache, similar to a browser.

 > Automatic handling of HTTP redirects

I actually don't know how well this works today. We're just using fetch, so if fetch() does it out of the box, so do we.

> Accept a callback to correct URLs that returned Moved Permanently and Permanent Redirect; which would provide the old and new URI, and the response body which may contain additional information on the redirect, and the user would update their database accordingly.

We don't really have an API for extracting this, but also don't fully understand the use-case.

> Automatic handling of throttling and Retry-After headers

The next version will have a fetch-middleware API, and this would be the perfect place to implement this.

> Automatic retry of PATCH requests as a PUT request, if the server does not have support
> Automatic retry of aborted downloads with a Range + If-Range request

Don't have this, and no plans for this.

> Monitoring of resource changes with If-Match, If-Modified-Since, and push events (maybe support CoAP's SUBSCRIBE method)

This is planned. Specifically, monitoring state changes and emitting events for these, along with subscribing via poll and in the future Websocket.

> Support for Code-on-Demand; the ability to apply stylesheets and scripts to downloaded resources

No real plans for this one either.



If you intend to develop a client that does this yourself, I would love to try to convince you to join forces. Regardless, this is a great list and I would love to check off some of these boxes. When it's not so late, I'm going to open individual tickets for these.

Cheers and thank you!
