### ISSUE TITLE
Support HTML forms

### ISSUE THREAD

**Issue by evert** [badgateway/ketting#199]
For a form like:

```html
<form method="POST" id="my-form" action="/register">
<input type="email" name="username" />
</form>
```

We may want an API such as:

```typescript
const someResource = ketting.go('/form.html');`
const state = await someResource.get();

const newState = await state.action('my-form').submit({
  name: 'me@evertpot.com',
});
```

cc @awwright

**Comment by awwright** [comment]
Yeah, that doesn't look bad. I don't see any need for anything complicated—probably most usage will be a single form field, like a search query, or something.

But do leave open the possibility of more complicated forms as an extension point, for example a DOM manipulation, or XForms, or something.

**Comment by evert** [comment]
Makes sense!
