### ISSUE TITLE
Expand usage examples

### ISSUE THREAD

**Issue by rnorden** [badgateway/ketting#213]
Hey,

so far ketting looks like a project where its creators put alot of thought into, kudos for that!
But I'm having trouble to understand how to use ketting effectively with Typescript.
So far I've created a service that calls my bookmark and follows the embedded array:
```typescript
async findAll(): Promise<Foo[]> {
    let foos: Resource<Foo>[] = await this.tables.followAll<Foo>("foo");
    return foos;
  }
```

- The returned `foos` is a `Resource<Foo>[]` so I have to call `get()` on the items within?
- `get()` returns a Promise itself so I have to clutter my code with async/await or callbacks?
- Once the Promises resolve I got the real resource representations. How would I follow their relationships?
  - Keep `get()`ting the resources (polluting the code)?
  - Keep track of both resources and resource representations?

**Comment by evert** [comment]
Hi!

In situations where you will need both to be able to follow links on resources, and work with their representations, you will keep track of both the resource and the result of `get()`.

Note that your code can be simplified to:

```typescript 
findAll(): PromiseLike<Foo[]> {
    return this.tables.followAll("foo");
}
```typescript


Ultimately the `Resource` is a reference to the endpoint, and you can either ask the current state, or set a new state.

In Ketting 6 we're making some changes though. An alpha is out already. We're doing a lot of work to make the experience more comfortable with React, and including a separate `react-ketting` package with hooks and HoC's.

A big difference is that the `get()` function will return a more full-fledged `State` object that has both information about its links, and the body. Once you get this `State` object from `.get()`, all the information is there and there's no need for promises and/or `await`.

What won't change though is to get a collection of items and then their bodies, it's still a two step process:

1. Get the resources
2. For each resource, get the state.

I noticed you use Angular. We're making a bunch of backwards compatibility changes, so I would be curious to hear if Ketting 6 solves some of the issues you are seeing. Angular-specific feedback is definitely appreciated.

**Comment by rnorden** [comment]
Hey, I'm using ketting in a second project by now. I'm thinking of preparing a pull request with a more complete tutorial on how to use ketting which complements your docs.

**Comment by evert** [comment]
That would be sweet! Where are you thinking of publishing it? We're getting close to a Ketting 6 release BTW which will have some changes, highly recommended to upgrade at this point.

Also, there is this new package for react https://www.npmjs.com/package/react-ketting

**Comment by evert** [comment]
We've made a huge amount of progress with react-ketting and ketting. I think this will solve most of the issues you've had
