### ISSUE TITLE
Add client.clearCache()

### ISSUE THREAD

**Issue by mattbishop** [badgateway/ketting#225]
I see that Resource has a clearCache() method that is automatically triggered by an unsafe method, which is good. However, the unsafe method usually has an impact on other resources that are also cached. As an example, take an address book API. This example API an `/addresses` list resource that has links to individual `/addresses/{id}` resources. If I follow the links from addresses to an individual address, then delete() that address, the cache for address is cleared, which is good. However, its parent `/addresses` resource is not cleared, so getting it again will reveal it still contains a link to the deleted address.

I am solving this problem in my code with this line:
```javascript
client.resourceCache = {}
```

It would be nicer to have a client.clearCache().

Also, I would like a config option to turn off caching altogether, at least until eTag support is in place.

**Comment by evert** [comment]
Hey @mattbishop ,

Ketting 6 is 99% stable, but it's released with a beta tag. What's missing right now is some documentation.
Ketting 6 does have `client.clearCache()`.

Ketting 6 also has support for not having a cache, or a 'very short cache' that expires after 30 seconds. The latter *usually* better to not get multiple hits for the same resource.

Lastly, both Ketting 5 and 6 allow you to return `Link: </addresses>; rel="invalidates"` after a `DELETE`, allowing you to control _from_ the server what cache side-effects an operation might have.

The docs have already been completely updated for Ketting 6 (we're close), and there's also an upgrade guide:

https://github.com/badgateway/ketting/wiki/Upgrading

**Comment by evert** [comment]
Closing this because I think it's solved, but feel free to use this thread for follow-up questions or concerns.

**Comment by evert** [comment]
If you do decide to upgrade to 6 before the 'final' release, would love to hear your feedback! Some stuff is definitely a bit different.

**Comment by mattbishop** [comment]
OK so this is in 6; I'm using 5.2.1. Have you published 6?

**Comment by evert** [comment]
Yes, with a `beta` tag

**Comment by evert** [comment]
So you'll need `npm i ketting@6.0.0.beta.0`

Full release is likely next week.
