### ISSUE TITLE
V6 doesn't recognize _embedded resources

### ISSUE THREAD

**Issue by mdhenriksen** [badgateway/ketting#229]
In version 5.2 `_embedded` resources won't trigger a request per entry, but version 6 won't recognize that the request contains `_embedded` resources and will instead make a `GET` request for each resources embedded.

Example:
```
 const articles = await ketting.follow('articles').followAll('articles')

    for (const resource of articles) {
      const state = await resource.get();
      console.log(state)
    }
```
The above code follows the root document link `articles` and then follows all embedded articles and logs them.

In version 5.2 it will simply log the `_embedded` resources from the initial request. But in version 6, the exact same code will trigger a `GET` request per entry.

**A workaround**
The following example is a possible workaround. But I'm not sure this is how it's intended to be used.
```
 const articles = await ketting.follow('articles')
 const fetchedArticles = await articles.get()

    for (const resource of fetchedArticles.embedded) {
      console.log(state)
    }
```

**Comment by evert** [comment]
That is very strange.. definitely a bug! nice catch. Would be ok sharing a sample HAL document? I'd like to make sure this is not some kind of edge case I missed, as I've not seen this problem myself.

**Comment by mdhenriksen** [comment]
> That is very strange.. definitely a bug! nice catch. Would be ok sharing a sample HAL document? I'd like to make sure this is not some kind of edge case I missed, as I've not seen this problem myself.

I thought it was a bug. I've pasted a copy of the HAL document below. I've tested version 5.2 and 6 with the exact same document yesterday which produced different results:

```
{
   "_embedded":{
      "articles":[
         {
            "id":"9d627132-ffdf-41bd-8e37-84af19fefd8d",
            "_links":{
               "self":{
                  "href":"{link_here}"
               },
               "link_1":{
                  "href":"{link_here}"
               },
               "link_2":{
                  "href":"{link_here}"
               },
               "link_3":{
                  "href":"{link_here}"
               }
            }
         },
         {
            "id":"e917e49a-7be3-4f6a-87fd-5e47a62ae97f",
            "_links":{
               "self":{
                  "href":"{link_here}"
               },
               "link_1":{
                  "href":"{link_here}"
               },
               "link_2":{
                  "{link_here}"
               },
               "link_3":{
                  "href":"{link_here}"
               }
            }
         },
         {
            "id":"e5227647-b8fb-4df7-ad7d-051b8c09dc2c",
            "_links":{
               "self":{
                  "href":"{link_here}"
               },
               "link_1":{
                  "href":"{link_here}"
               },
               "link_2":{
                  "href":"{link_here}"
               },
               "link_3":{
                  "href":"{link_here}"
               }
            }
         }
      ]
   },
   "_links":{
      "self":{
         "href":"{link_here}"
      }
   }
}
```

**Comment by evert** [comment]
Are the `self` urls in your embedded resources absolute or relative? If they are relative, I would also be curious what pattern they follow...

**Comment by evert** [comment]
Also, what mime type does your server emit?

**Comment by evert** [comment]
Ok, different take... given that:

1. Embedded items are parsed and are available via `fetchArticles.embedded`
2. The cache is actually not honored

The best theory I have for this is that there is a difference between the uri you are trying to follow/fetch and what is specified in `embedded`.

So , I would be curious what the `uri` is for each item in `fetchArticles.embedded` and if this uri is what you expect it to be.

**Comment by mdhenriksen** [comment]
Thanks for looking into it! I've tested it with your sample code above and the result are identical. 

Regarding `caching` I've noticed that `embedded` resources are not cached. E.g. console logging `fetchedArticles` will on first render (I'm using React) return an object with the articles embedded, but a subsequent render will return the same object _with embedded array being empty_. Could this be related to the issue? I've tested this with the code below.

```
 const articles = await ketting.follow('articles')
 const fetchedArticles = await articles.get()
 console.log(fetchedArticles)

    for (const resource of fetchedArticles.embedded) {
      console.log(resource.uri)
    }
```

---
_The code I did the URI test with for reference_
```
const rootResource = ketting.go();
    const articlesResource = await rootResource.follow("articles").followAll("articles")

    for (const article of articlesResource) {
      console.log(article.uri)
    }
```

```
 const rootResource = ketting.go();
    const articlesResource = await rootResource.follow("articles")
    const articles = await articlesResource.get()

    for (const article of articles.embedded) {
      console.log(article.url)
    }
```

**Comment by evert** [comment]
The embedded items disappearing is actually by design. The `embedded` property on state is not really intended to be used directly. The first time the state arrives, it's there and place in the cache.

The second time you call `.get()`, the State comes from the cache with the embedded items stripped. These cached items *should* still exist in `ketting.cache`, so you could check `ketting.cache.get('...someurl')` to see if it's still there.

I'm assuming the answer to this is going to be 'no', but you are only making 1 instance of the client object in your application right? There should ideally be only one case where you call something like `const ketting = new Ketting('...')`, because if this happens once per render, you'll also have 1 completely new cache per render.

Unfortunately I'm getting a bit lost in terms of what the issue could then be... I don't suppose there's a way I could look at the application so I can put some breakpoints and trace what's happening?

**Comment by mdhenriksen** [comment]
> The embedded items disappearing is actually by design. The embedded property on state is not really intended to be used directly. The first time the state arrives, it's there and place in the cache.

I understand. However, since v6 makes multiple requests on `embedded` resources, I have to workaround it somehow.

> I'm assuming the answer to this is going to be 'no', but you are only making 1 instance of the client object in your application right? There should ideally be only one case where you call something like const ketting = new Ketting('...'), because if this happens once per render, you'll also have 1 completely new cache per render.

I do only have 1 place where I instantiate Ketting with `const ketting = new Client('...');`. I've created a context wrapping the App, so all components can access and use that instance. I've tested the exact same setup with v5 and v6 and only v6 makes a request per item embedded. So I'm rather confident that it's version 6 that changes something and my implementation, but I'm open to test things out if you have more suggestions :+1: 

> Unfortunately I'm getting a bit lost in terms of what the issue could then be... I don't suppose there's a way I could look at the application so I can put some breakpoints and trace what's happening?

It's a project for the company I work at, so I can unfortunately not give you any access to the application.. I realize this would make debugging easier.

**Comment by obicloud** [comment]
Same problem here, club.get() call does GET request

`function App() {
  const client = new Client('http://localhost:7070/rugbyau/api/v1/');

  const [data, setData] = useState<any>([]);

  useEffect(() => {
    console.log('Loading....');
    loadClubs();
  }, []);

  const loadClubs = async () => {
    const home = client.go();
    console.log(home);
    const resource = await home.follow('clubs');
    console.log(resource);
    const clubs = await resource.followAll('clubs');
    console.log(clubs);
    const xxx = await Promise.all(clubs.map(club => club.get()));
    console.log(xxx);
    setData(xxx);
  }

  return (
    <div className="App">
      <header className="App-header">
        <ul>
          { data.map((club:any) => (<li key={club.uri}>{club.data.name}</li>)) }
        </ul>
      </header>
    </div>
  );
}
`
Response from http://localhost:7070/rugbyau/api/v1/clubs
 
`
{
  "_embedded" : {
    "clubs" : [ {
      "name" : "xSeaforth-Balgowlah Raiders Junior Rugby Union Football Club",
      "address" : null,
      "contactName" : null,
      "contactEmail" : null,
      "lat" : -33.796,
      "lng" : 151.238,
      "website" : "http://www.raidersrugby.com.au",
      "_links" : {
        "self" : {
          "href" : "http://localhost:7070/rugbyau/api/v1/clubs/3"
        },
        "club" : {
          "href" : "http://localhost:7070/rugbyau/api/v1/clubs/3"
        },
        "xplorerClub" : {
          "href" : "http://localhost:7070/rugbyau/api/v1/clubs/3/xplorerClub{?projection}",
          "templated" : true
        },
        "parentClub" : {
          "href" : "http://localhost:7070/rugbyau/api/v1/clubs/3/parentClub"
        }
      }
    }, {
      "name" : "Collaroy Cougars Junior Rugby Club",
      "address" : "Anzac Ave, Collaroy NSW 2097, Australia",
      "contactName" : null,
      "contactEmail" : null,
      "lat" : -33.738018,
      "lng" : 151.297562,
      "website" : "https://collaroyrugby.com.au",
      "_links" : {
        "self" : {
          "href" : "http://localhost:7070/rugbyau/api/v1/clubs/4"
        },
        "club" : {
          "href" : "http://localhost:7070/rugbyau/api/v1/clubs/4"
        },
        "xplorerClub" : {
          "href" : "http://localhost:7070/rugbyau/api/v1/clubs/4/xplorerClub{?projection}",
          "templated" : true
        },
        "parentClub" : {
          "href" : "http://localhost:7070/rugbyau/api/v1/clubs/4/parentClub"
        }
      }
    } ]
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost:7070/rugbyau/api/v1/clubs"
    },
    "profile" : {
      "href" : "http://localhost:7070/rugbyau/api/v1/profile/clubs"
    }
  }
}`

**Comment by evert** [comment]
@madsmadsen identified the core issue, I'm very grateful. The reason I hadn't seen this is (sadly) because we were running a version of ketting 6 slightly older than current, and it's a relatively new change.

PR and release will follow in the next 30 minutes.

Thank you @madsmadsen and everyone sending their debug information. Apologies for not spotting the error earlier.

**Comment by evert** [comment]
ketting 6.0.0-beta.1 is released. Mind giving it a spin?

**Comment by mdhenriksen** [comment]
Hey @evert! I can confirm that `6.0.0-beta.1` fixed the issue. :rocket:

**Comment by evert** [comment]
NICE!
