### ISSUE TITLE
Support for "JSON Hypermedia Links"?

### ISSUE THREAD

**Issue by mattbishop** [badgateway/ketting#237]
I discovered that a hypermedia API I wrote years ago pretty much follows this draft RFC: https://tools.ietf.org/id/draft-wparad-json-links-02.html

Might be easy to add to Ketting?

**Comment by evert** [comment]
The `links` object doesn't seem all that difficult. The spec is a bit hard to read, so it's not entirely clear if the embedded resources (with `self` links) can be treated similarly to embedded resources in HAL (are they a full representation?).

The requirement for all uris being absolute is also a little strange.

My sense is that this doesn't feel like a very high quality specification (yet), so I'm a little hesitant adding first-class support for it.

Worth noting is that ketting's format parser is extensible, so it should be possible to register your own parsers...

**Comment by evert** [comment]
Closing this on the basis that I don't feel the mentioned draft is in a stage yet where it's worth adding support for it.

If this is interesting to you personally, I'd encourage you to write your own `stateFactory` and `State` class, which is all that's needed to add support for additional formats.
