### ISSUE TITLE
API path in folder (React)

### ISSUE THREAD

**Issue by johnnypea** [badgateway/ketting#247]
When my API is located folder:
`const client = new Client("https://example.com/wp-json/wp/v2/");`
and call my endpoint with slash in the beginning:
`const { loading, error, data } = useResource("/posts");`
I get it calls `https://example.com/posts` instead of `https://example.com/wp-json/wp/v2/posts`.

Is this the intended output? It works without slash but I would prefer slashes to be stripped automatically in cases like this.

**Comment by evert** [comment]
Hi!

Urls work similar to how they work in browsers. If you open a website at `https://example/A/B/C`, and you add a link pointing to `/D`, the `/A/B/C` portion will get stripped.

So, to make this work, remove the `/` in front of `posts`:

      const { loading, error, data } = useResource("posts");
