### ISSUE TITLE
Object of objects instead of array of objects in data

### ISSUE THREAD

**Issue by johnnypea** [badgateway/ketting#248]
`const myPostState = await myPostRes.get();` returns object of objects instead of array of objects in `myPostState.data`

```
{
  '0': {
    id: 32
  },
  '1': {
    id: 8
  }
}
```

Raw API response
`[{"id":32},{"id":8}]`

How could I make it to return an array? Thanks.

**Comment by evert** [comment]
This is for sure a bug.

**Comment by evert** [comment]
accidental push to master =( this is fixed though, releasing shortly.
