### ISSUE TITLE
Embedded items in application/hal+json are not deserialized/cached

### ISSUE THREAD

**Issue by Gearme** [badgateway/ketting#275]
Given a HAL+JSON response such as the following, `getEmbedded()` on the State of the resource returns an empty array for me.

```
{
  "_embedded": {
    "animals": [
      {
        "name": "dog",
        "animalType": "MAMMAL",
        "_links": {
          "self": {
            "href": "http://localhost:8080/clinic/animals/1"
          },
          "animal": {
            "href": "http://localhost:8080/clinic/animals/1{?projection}",
            "templated": true
          }
        }
      }
    ]
  },
  "_links": {
    // snip!
  },
  "page": {
    // snip!
  }
}
```

**Comment by evert** [comment]
Hi @Gearme , could this be the same issue as #273 ?

**Comment by Gearme** [comment]
The possibility had occurred to me - but since they explicitly mentioned the data not being there on the *second* call, I don't believe so.

**Comment by evert** [comment]
What does still apply is that you should use follow to get related resources instead of getEmbedded.

It's possible that something happened earlier that caused you to have a warm cache for this resource

**Comment by evert** [comment]
Closing due to no response, but feel free to comment here in case this is still an issue.
