### ISSUE TITLE
Templated links without template data don't work

### ISSUE THREAD

**Issue by sazzer** [badgateway/ketting#302]
I've been playing with Ketting, and found a slight oddity with templated links.

If I have a link of:
```
    "tag:hal,2020:users": {
      "href": "/users{?offset,count}",
      "templated": true
    }
```

Then I get different results if I execute the following:
* `homeRes.follow("tag:hal,2020:users").get()`
* `homeRes.follow("tag:hal,2020:users", {}).get()`

The first of those calls a URL of `/users%7B?offset,count%7D`. The second calls `/users`.

It seems that, because the link itself indicates that it's templated, both should use `/users` instead of the client needing to know if the link is templated or not.

**Comment by evert** [comment]
Def sounds like a bug!

**Comment by Gearme** [comment]
I agree - would be nice to get rid of the {} everywhere ;)
