### ISSUE TITLE
Ketting always overrides HTTP cache for initial request

### ISSUE THREAD

**Issue by sazzer** [badgateway/ketting#324]
When making the initial request to the home document, Ketting is always sending the headers:
```
Cache-Control: no-cache
Pragma: no-cache
```

This is then forcing the HTTP request to go all the way to the server, *even if any intermediate caches have a version available*. In particular, because home documents likely don't change often, they could have a cache timeout that means they don't need to be re-requested very often at all. However, this is completely ignored by this and causes more load to reach the server needlessly.

For reference, the code I'm using for this is simply:
```
import { Client } from "ketting";

const client = new Client("http://localhost:8000");
const rootRes = client.go("/");
await rootRes.get();
```

**Comment by evert** [comment]
Confirmed. We need a way to not send this header on `.get()`, but send it on `.refresh()`. Should not be a super hard fix.
