### ISSUE TITLE
No facility to set fetch 'credentials' option

### ISSUE THREAD

**Issue by dayre** [badgateway/ketting#403]
I really want to use this library, but am unable to at the moment as there is no facility to set the credentials option in fetch. 
 
Way back when, there used to be a fetchInit used with a new Ketting instance, but with the move to Client it looks like this has been removed... so it seems there is no facility to set global fetch init options or per options per request.    Middleware only gives you access to the already created Request and credentials are readonly.

**Comment by evert** [comment]
Hey @dayre ,

MIddleware is indeed what is supposed to replace this. Here's an example of creating a new request, based on an old request and overriding settings:

```typescript
const r = new Request('https://example', { method: 'POST'});
const r2 = new Request(r, { credentials: 'include' });
```

Does that solve your problem?

**Comment by dayre** [comment]
Thank you for the quick reply @evert  !   I didn't realize there was a copy constructor available for Request, that works greet thank you.
