### ISSUE TITLE
bearerAuth not working / not documented

### ISSUE THREAD

**Issue by rome-legacy** [badgateway/ketting#410]
Hi,

i am working on an angular app which gets data from a spring boot rest service. without auth everything was working fine. now i have introduced authentication based on keycloak. my http service which has been pimped with http interceptors works fine with bearer token auth against some other endpoints, but ketting client seems not to work.
also i could not find any documentation how to use ketting with a bearer token.

consider this easy function:

```
  public async getTime(id: string): Promise<Time> {
    const token: string = await this.authService.getToken();
    this.logger.debug('use token for ketting client', token);
    this.client.use(bearerAuth(token));
    return this.client.go<Time>(`time/${id}`).get().then((state: State<Time>) => state.data);
  }
```
token is being logged correctly but i still get 401 response status and i also do not see any **authorization header** being sent within response.
but when i copy the logged token and use it with postman against the api, then everything is fine.

maybe i'm using it incorrect?

i'm using 
angular 12.2.13
ketting 7.2.0

a quick response is very welcomed  :-D

regards
rome

**Comment by evert** [comment]
Strange! The bearerAuth middleware is rather simple. Could this be an issue related to Cors?

**Comment by rome-legacy** [comment]
hey,
thx for the response.
to your points:
- cors: tbh, i had some issues with cors last couple of days, but now it seems to work and is only an issue if authentication has failed, then required headers are not set. but with successful auth that shouldnt be a problem anymore.
- multiple/parallel requests: this one could be ruled out
- other middlewares: no, ketting is currently used only with one service, still experimental :-)

so, i will try your debug solution, lets see, what happens

regards

**Comment by rome-legacy** [comment]
uff, i'm sorry for bothering...
i had a stupid copy/paste error.
it is working now, damn!

have a nice evening
regards

**Comment by evert** [comment]
Great to hear it!
