### ISSUE TITLE
Allow LinkVariables to support multiple values with the same key

### ISSUE THREAD

**Issue by dayre** [badgateway/ketting#421]
Really enjoying building a client side data access layer using Ketting, thank you for making it !

Have an issue at the moment supporting sort using multiple fields.   My backend is a Spring Data Rest, and the method for sorting by multiple fields is to repeat the "sort" parameter for each field  (e.g. ?sort=name,asc&sort=created,desc).   

I'm using the LinkVariables param on the follow() method in Resource, but it is defined as a map and doesn't permit duplicate keys.

- https://stackoverflow.com/questions/33018127/spring-data-rest-sort-by-multiple-properties
- https://stackoverflow.com/questions/24059773/correct-way-to-pass-multiple-values-for-same-parameter-name-in-get-request

Since there doesn't look to be anything in the RFC for query params that disallows multiple values, i'm thinking LinkVariables should be redefined to support this.

Looking at the API, I don't see any workarounds  that would allow me to make this happen... unless you have any suggestions ?

**Comment by evert** [comment]
Ah interesting. What would the URI Template look like for these?

**Comment by dayre** [comment]
This is an example from my "clients" link.   Page,size,projection are single values, whereas sort can be a collection/multiple.   
`
"clients": {
            "href": "http://localhost:8080/api/clients{?page,size,sort,projection}",
            "templated": true
        },
`

Spring documents it here: https://docs.spring.io/spring-data/rest/docs/current/reference/html/#repository-resources.collection-resource.supported-methods.get  : 

"A collection of sort directives in the format ($propertyname,)+[asc|desc]?."

**Comment by evert** [comment]
I wonder if we could just type LinkVariables as:

```typescript
/**
 * A key->value map of variables to place in a templated link
 */
export type LinkVariables = {
  [key: string]: string | number | (string|number)[]
};
```

**Comment by dayre** [comment]
Ok, interesting rabbit hole, just delved into the URI template RFC.   I think your suggested change is needed and will work.

The issue is that Spring data expects multivalues for sort to be "expanded" by duplicating the key for each entry.    (see https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#core.web.basic, Table 1).   

If i use the template provided by Spring, i get the following:
```js
const templ = uriTemplate.parse("http://localhost:8080/api/clients{?page,size,sort,projection}");
const expanded = templ.expand({sort : ["id,asc", "lastModifiedDate,desc"]});

// http://localhost:8080/api/clients?sort=id%2Casc,lastModifiedDate%2Cdesc
```


Spring doesn't parse this properly and the sort direction for the params isn't handled properly (they both end up with a sort direction of "DESC").   

If i modify the template to include the expansion modifier (*) for sort in the URI template, i get what Spring expects:
```js
const templ = uriTemplate.parse("http://localhost:8080/api/clients{?page,size,sort*,projection}");
const expanded = templ.expand({sort : ["id,asc", "lastModifiedDate,desc"]});

// http://localhost:8080/api/clients?sort=id%2Casc&sort=lastModifiedDate%2Cdesc
```


This works great and Spring is happy, all is good with the world. 


So given your suggested change, and the proper template i should be able to generate the URL Spring expects.  I still need to follow up to see why Spring isn't providing the expansion modifier on the sort variable which i think it should be, but for this issue if your change is made that should do it.

**Comment by dayre** [comment]
For reference, anyone else dealing with this issue when using your spectacularly amazing stupendous library and the lack of an explosion modifier for the sort parameter generated by Spring, i've opened an issue here:

https://github.com/spring-projects/spring-data-commons/issues/2531

**Comment by qmachard** [comment]
> I wonder if we could just type LinkVariables as:
> 
> ```ts
> /**
>  * A key->value map of variables to place in a templated link
>  */
> export type LinkVariables = {
>   [key: string]: string | number | (string|number)[]
> };
> ```

Yes, it works !

**Comment by dayre** [comment]
Hi Evert, i don't see this commit in any releases, it's not in 7.5.1.   Did it get overlooked ?
