### ISSUE TITLE
Resource.uri ignores the returned self link

### ISSUE THREAD

**Issue by reda-alaoui** [badgateway/ketting#423]
I am not sure it is a bug.

Let be a resource user with id 1 and with username jdoe accessible at the following urls:
- `https://example.org/users/1`
- `https://example.org/usernames/jdoe/user`

We consider that `https://example.org/users/1` is the canonical uri of the user.

On a GET to `https://example.org/usernames/jdoe/user`, the server produces:
```json
{
  "username": "jdoe",
  "_links": {
    "self": {
      "href": "https://example.org/users/1"
    }
  }
}
```

Now, using Ketting we execute the same request with:
```javascript
const userResource = ketting.go('https://example.org/usernames/jdoe/user');
console.log(`${userResource.uri}`); // prints "https://example.org/usernames/jdoe/user"
const userState = await userResource.get();
console.log(`${userState.uri}`); // prints "https://example.org/usernames/jdoe/user"
console.log(`${userState.links.get('self').href}`); // prints "https://example.org/usernames/jdoe/user"
```

It seems that the url from which we retrieve the resource irremediably becomes the `uri` and the self link of the `Resource` and the `State`. 

I find this behaviour surprising. Does it work as expected? Am I expected to wrap the representation of `https://example.org/usernames/jdoe/user` in an `_embedded` attribute?

**Comment by evert** [comment]
Hi @reda-alaoui ,

To me HAL (and other standards) aren't fully clear on what to do if `self` does not match the uri. I know originally the `self` link was introduced in Atom mainly for 2 cases:

1. Embedded items
2. Cases where the original context is lost. Maybe an Atom parser does not have access to the URI of the original request, and just a response body to work with.

So in my opinion a self link not matching the request URI is maybe a server bug? My initial intuition is that it might be good to emit a warning whenever this happens. There is a separate `canonical` link relationship, but the canonical link still wouldn't really 'replace' the original.

So I'd be curious why you'd need this!

**Comment by evert** [comment]
Just doing a bit of house cleaning. I'm happy to keep discussing here if you like, but closing this ticket in case there's nothing more to say.
