### ISSUE TITLE
Cached state losing embedded data

### ISSUE THREAD

**Issue by dayre** [badgateway/ketting#428]
I have an issue when i'm fetching a resource with embedded data, after calling get() which returns the state object with the embedded data present, subsequent calls to get() on the same resource returns a state object without the embedded data.  

I noticed that before state is plopped into the cache, it is cloned first, and that clone method isn't using the embedded property when initializing a cloned state.  

Is this by design ?  Shouldn't the full state being cached include the embedded property ?

```js
///  base-state.ts
clone(): State<T> {

    return new BaseState({
      client: this.client,
      uri: this.uri,
      data: this.data,
      headers: new Headers(this.headers),
      links: new Links(this.links.defaultContext, this.links.getAll()),
      actions: this.actionInfo,
    });

  }
```

**Comment by evert** [comment]
This question comes up a lot, so there's definitely a UX problem here... but it is by design. See #407 for more info.

You're meant to `.follow` items in `_embedded` to get access to them. Anything that was in `_embedded` exists in your cache.

**Comment by dayre** [comment]
Ah, sorry i completely missed these other discussions.

I think there definately is a UX issue here.   When i call get() the first time (uncached), embedded is part of the returned "state".   But once it is cached, this particular part of the state no longer exists.    It's counter intuitive to have the state of something changed when cached.  That's confusing.

I'm using Spring Data, and my particular resouce is an "[association resource](https://docs.spring.io/spring-data/rest/docs/current/reference/html/#repository-resources.association-resource)" in Spring terms (e.g. /car/X/parts).   In my case, this association resource is returning an array of embedded resources.   In Ketting terms i assumed that those embedded items are the "state" for that association resource... so was expecting it to be cached and present upon subsequent calls.   

It's great the individual items are cached, but right now i'm having to call refresh() on the association resource each time to ensure i get the embedded data back (as once it is cached it is lost)... so i can't take advantage of Ketting's caching for these association resources.

**Comment by evert** [comment]
Hi Dayre,

Those embedded resources are not lost though, they are just stored as individual resources in the main client cache.
So if for example those resources were embedded with the rel `item`, you can still get to them by calling:

```
const itemResources = state.followAll('item')
```

**Comment by evert** [comment]
I updated the docs a bit to describe the current behavior. Let me know if you have further thoughts here; I'm happy to keep discussing.

**Comment by dayre** [comment]
Thank you for your patience and thoughtful replies Evert, i'm still a bit riddled.   Below is a JSON example of what i'm dealing with from Spring, a fairly typical result from an "Association resource", here i have a property which has many property maintenance systems which i'm trying to retrieve via the endpoint.

```
http://localhost:8080/api/properties/9340c73b-140d-47e7-a274-05ad1cc9be4d/maintenanceSystems?projection=propertyMaintenanceSystemSummary
```

Default behavior for Spring Data REST provides no links corresponding to the individual items within the embedded array.   I think this is behavior i could make happen by adding them to the _links section, but something i would have to do individually for each one/many - many/many  association in my domain model.   I'm guessing that currently using followAll() won't work with this output until issue #409 is back in action ?

If so, i think there is still an issue with no link variables allowed on followAll() as there is with follow().   It's common in Spring to provide "projections" to return different shapes to the underlying entities, but i wouldn't be able to specify which projection to use as no URI templates could be used as there are no link variables to pass in ?



```json
{
    "_embedded": {
        "propertyMaintenanceSystems": [
            {
                "maintenanceSystemParentId": 1,
                "archived": false,
                "maintenanceSystemName": "Water",
                "maintenanceSystemId": 2,
                "id": 610,
                "_links": {
                    "self": {
                        "href": "http://localhost:8080/api/propertyMaintenanceSystems/610"
                    },
                    "propertyMaintenanceSystem": {
                        "href": "http://localhost:8080/api/propertyMaintenanceSystems/610{?projection}",
                        "templated": true
                    }
                }
            },
            {
                "archived": false,
                "maintenanceSystemName": "Maintenance Systems",
                "maintenanceSystemId": 1,
                "id": 611,
                "_links": {
                    "self": {
                        "href": "http://localhost:8080/api/propertyMaintenanceSystems/611"
                    },
                    "propertyMaintenanceSystem": {
                        "href": "http://localhost:8080/api/propertyMaintenanceSystems/611{?projection}",
                        "templated": true
                    }
                }
            },
            {
                "maintenanceSystemParentId": 2,
                "archived": false,
                "maintenanceSystemName": "Water Treatment",
                "maintenanceSystemId": 6,
                "id": 612,
                "_links": {
                    "self": {
                        "href": "http://localhost:8080/api/propertyMaintenanceSystems/612"
                    },
                    "propertyMaintenanceSystem": {
                        "href": "http://localhost:8080/api/propertyMaintenanceSystems/612{?projection}",
                        "templated": true
                    }
                }
            }
        ]
    },
    "_links": {
        "self": {
            "href": "http://localhost:8080/api/properties/9340c73b-140d-47e7-a274-05ad1cc9be4d/maintenanceSystems?projection=propertyMaintenanceSystemSummary"
        }
    }
}
```

**Comment by evert** [comment]
Ah yes, #409 is exactly for fixing this issue. Although fixing the server is obviously probably better!

I am a bit confused actually. I had a brief look at the code, and there's logic there for it:

https://github.com/badgateway/ketting/blob/main/src/state/hal.ts#L148

If you feel like taking a look at it for fixing #409, it can definitely expedite this!

But based on your example, this is how Ketting should work (although it may not right now):


```typescript
const resource = client.go('http://localhost:8080/api/properties/9340c73b-140d-47e7-a274-05ad1cc9be4d/maintenanceSystems?projection=propertyMaintenanceSystemSummary');
const state = await resource.get();

for(const propertyMaintenanceSystem of state.followAll('propertyMaintenanceSystems')) {
  console.log(propertyMaintenanceSystem);
}
```

**Comment by dayre** [comment]
Thanks for that succinct bit of code,  I'm off and running again !  and #409 does look to be a non issue....

:pray:
