### ISSUE TITLE
"placeholder" property misspelled "placeHolder" in hal.ts

### ISSUE THREAD

**Issue by dayre** [badgateway/ketting#459]
I'm using Spring HATEAOS which i can see is setting the placeholder property correctly but it isn't coming through in Ketting. 

According to the HAL spec, it seems to be refered to as "placeholder", but in the hal.ts, it is looking at the halField "placeHolder" property with a capital "H".

From Spring:
```
"method": "POST",
            "properties": [
                {
                    "name": "cascade",
                    "prompt": "Apply to child systems ",
                    "placeholder": "When set, will copy report into subsystems / components. "
                },
```

https://github.com/badgateway/ketting/blob/6880d09c2e2db231a0f9f48a7b516d8ae4680114/src/state/hal.ts#L337

I believe this is a typo in hal.ts ?     If so, i can submit a PR for it... just wanted to confirm.

**Comment by evert** [comment]
Yes, seems like this is a typo! PR is appreciated!

**Comment by dayre** [comment]
I added another PR for hal-types which this change needs.   

https://github.com/badgateway/hal-types/pull/105

Not sure how best to deal with these cross repo dependency updates other than the separate PR's for each.    Couldn't verify the changes to the tests without the hal-types PR in place.   If there is an alternate way you prefer to handle these in the future, please let me know.
