### ISSUE TITLE
Ability to have preferTransclude enabled on any FollowPromise by default

### ISSUE THREAD

**Issue by reda-alaoui** [badgateway/ketting#473]
Hi,

I think it'd be nice to be able to ask `Ketting` to enable `preferTransclude` by default.
It'd take the form of an additional flag in `Client`.

If it's ok for you, I can create a PR for that.

**Comment by reda-alaoui** [comment]
I think I initially misunderstood the purpose of `preferTransclude`. 
I thought I would use it as a relation's filter.

Closing this one then :)

**Comment by evert** [comment]
Makes sense! `preferTransclude` is a way for a client to indicate: "I would prefer it if you embedded the resources with this rel"
