### ISSUE TITLE
Expand templated link without following

### ISSUE THREAD

**Issue by chadkouse** [badgateway/ketting#488]
Hi - this may already exist but I can't find it.

Basically I have a (HAL) API that is including some `_links` -- and I want to just get the final expanded url of a particular rel after variable substitution without actually following the link.  Following works but generates an HTTP request which I don't want/need.

I thought I could use the link method on the resource but it doesn't appear to accept linkvariables so it doesn't expand.  Not to mention it's marked deprecated.

Can anyone point me in the right direction here?  Love the library btw!

**Comment by evert** [comment]
Following a link generally does not cause a HTTP request. Initially you only get a reference to the target resource, but we're not assuming that you'll want to `GET` that resource.

So the easiest way to do this, is to follow the link after all, and then using `resource.uri`. Or do you have other reasons why you don't want to `.follow()` ?

**Comment by evert** [comment]
Closing due to no feedback
